cluster_label: "test_cluster"

provider: "aws-spot"
region: "us-east-1"
availability_zone: "us-east-1a"
aws_secret_key: "your aws secret key"
aws_access_key: "your aws access key"

private_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa"
public_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa.pub"
public_key_name: "vanderlei@RIVET-LABS-MAC-HGMW6NW46J"

master_ami: "ami-0f79feff35a0952f8"
master_ebs: 10
master_rbs: 10
master_instance_type: "t2.micro"

worker_count: 1
worker_ami: "ami-0f79feff35a0952f8"
worker_ebs: 10
worker_rbs: 10
worker_instance_type: "t2.micro"
worker_spot_price: 0.5
