version: '3'
services:
  postgres:
    image: docker.io/postgres:latest
    container_name: hpcc-services-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql

  minio:
    image: minio/minio:latest
    container_name: hpcc-services-minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio/data:/data/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: minio server /data/minio --console-address ":9090"
